### ISSUE TITLE
How to run game?

### ISSUE THREAD

**Issue by alex-aparin** [RamziKahil/MarioDemo#1]
I tried to run game, but it don't work. I am tried to do following steps:
1) Move to root directory of game
2) Run command from terminal (Cygwin64) - node server.js (node command is not recognized)

What did I make wrong?

**Comment by 0xRamsi** [comment]
Hello Alexander,
I am very sorry that I am answering only now, I just found out that the notifications have been getting to the spam-folder.

Have you installed the server software? https://nodejs.org/en/
I may have written it unclear, `node` is not a standard tool you get with any OS.

Best regard,
Ramzi
